
apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action-service
  template:
    metadata:
      labels:
        app: action-service
    spec:
      containers:
        - name: action-service
          image: story-action-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: action-service
spec:
  ports:
    - port: 5002
      targetPort: 5002
  selector:
    app: action-service
