apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scenario-gen-scaler
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: scenario-gen
  minReplicaCount: 2
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: battle-gen-scaler
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: battle-gen
  minReplicaCount: 2
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
