apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-broker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-broker
  template:
    metadata:
      labels:
        app: redis-broker
    spec:
      containers:
        - name: redis
          image: "redis:6.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: broker-storage
              mountPath: /data
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: redis-broker-pvc
