name: CI Chain

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io/ragingsnake/mc-app

jobs:
  sys-scan:
    runs-on: self-hosted
    container:
      image: nikolaik/python-nodejs:python3.10-nodejs18
    
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        service:
          - { name: "frontend", path: "./frontend" }
          - { name: "api-gateway", path: "./backend/api-gateway" }                                                                                      
          - { name: "story-orchestrator", path: "./backend/story-orchestrator" }
          - { name: "scenario-gen", path: "./backend/scenario-gen" }
          - { name: "battle-gen", path: "./backend/battle-gen" }
          - { name: "character-gen", path: "./backend/character-gen" }
          - { name: "endings-gen", path: "./backend/endings-gen" }
          - { name: "story-db-service", path: "./backend/story-db-service" }                                                                            

    steps:
    - name: Pull repo
      uses: actions/checkout@v4

    - name: Install Docker CLI
      run: |
        apt-get update && apt-get install -y docker.io

    - name: Lint check
      working-directory: ${{ matrix.service.path }}
      run: |
        if [ "${{ matrix.service.name }}" = "frontend" ]; then
          rm -rf node_modules package-lock.json
          npm install
          npm install @oxlint/binding-linux-x64-gnu
          npm run lint
          npm run build
        else
          python -m py_compile app.py
        fi
    
    - name: Trivy Filesystem Scan (The Docker Way)
      working-directory: ${{ matrix.service.path }}
      run: |
        # Blame Bosch for making me do this
        cat <<EOF > Dockerfile.trivy
        FROM aquasec/trivy:latest
        COPY . /app-to-scan
        WORKDIR /app-to-scan
        EOF
        
        docker build -f Dockerfile.trivy -t disposable-trivy-scanner .
        docker run --rm \
          -e http_proxy -e https_proxy -e no_proxy -e HTTP_PROXY -e HTTPS_PROXY -e NO_PROXY \
          disposable-trivy-scanner fs --db-repository public.ecr.aws/aquasecurity/trivy-db:2 --severity CRITICAL,HIGH --exit-code 1 .

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u "ragingsnake" --password-stdin

    - name: Build Docker Image
      working-directory: ${{ matrix.service.path }}
      run: |
        docker build \
          --build-arg HTTP_PROXY=$HTTP_PROXY \
          --build-arg HTTPS_PROXY=$HTTPS_PROXY \
          --build-arg NO_PROXY=$NO_PROXY \
          --build-arg http_proxy=$http_proxy \
          --build-arg https_proxy=$https_proxy \
          --build-arg no_proxy=$no_proxy \
          -t ${{ env.REGISTRY }}:${{ matrix.service.name }}-${{ github.sha }} .

    - name: Push Docker Image
      run: |
        docker push ${{ env.REGISTRY }}:${{ matrix.service.name }}-${{ github.sha }}
    